/* Dolanan service worker — cache-first precache of app shell + games.
 * AUTO-GENERATED by scripts/build-sw.mjs. Do not hand-edit the ASSETS list;
 * run `node scripts/build-sw.mjs` after adding/renaming files.
 */
const VERSION = "dolanan-20260417041231";

const ASSETS = [
  "/",
  "/games.js",
  "/games/battleship/",
  "/games/battleship/game.css",
  "/games/battleship/game.js",
  "/games/battleship/index.html",
  "/games/checkers/",
  "/games/checkers/game.css",
  "/games/checkers/game.js",
  "/games/checkers/index.html",
  "/games/chess/",
  "/games/chess/bot.js",
  "/games/chess/game.css",
  "/games/chess/game.js",
  "/games/chess/index.html",
  "/games/congklak/",
  "/games/congklak/game.css",
  "/games/congklak/game.js",
  "/games/congklak/index.html",
  "/games/connect-four/",
  "/games/connect-four/game.css",
  "/games/connect-four/game.js",
  "/games/connect-four/index.html",
  "/games/dots-and-boxes/",
  "/games/dots-and-boxes/game.css",
  "/games/dots-and-boxes/game.js",
  "/games/dots-and-boxes/index.html",
  "/games/hangman/",
  "/games/hangman/game.css",
  "/games/hangman/game.js",
  "/games/hangman/index.html",
  "/games/hangman/words.js",
  "/games/ludo/",
  "/games/ludo/game.css",
  "/games/ludo/game.js",
  "/games/ludo/index.html",
  "/games/tictactoe/",
  "/games/tictactoe/game.css",
  "/games/tictactoe/game.js",
  "/games/tictactoe/index.html",
  "/games/truth-or-dare/",
  "/games/truth-or-dare/game.css",
  "/games/truth-or-dare/game.js",
  "/games/truth-or-dare/index.html",
  "/games/truth-or-dare/prompts.js",
  "/games/werewolf/",
  "/games/werewolf/game.css",
  "/games/werewolf/game.js",
  "/games/werewolf/index.html",
  "/hub.css",
  "/hub.js",
  "/icons/apple-touch-icon.png",
  "/icons/favicon.ico",
  "/icons/favicon.png",
  "/icons/favicon.svg",
  "/icons/games/battleship.svg",
  "/icons/games/checkers.svg",
  "/icons/games/chess.svg",
  "/icons/games/congklak.svg",
  "/icons/games/connect-four.svg",
  "/icons/games/dots-and-boxes.svg",
  "/icons/games/hangman.svg",
  "/icons/games/ludo.svg",
  "/icons/games/tictactoe.svg",
  "/icons/games/truth-or-dare.svg",
  "/icons/games/werewolf.svg",
  "/icons/icon-192-maskable.png",
  "/icons/icon-192.png",
  "/icons/icon-512-maskable.png",
  "/icons/icon-512.png",
  "/index.html",
  "/manifest.webmanifest",
  "/offline.html",
  "/og-image.png",
  "/shared/board.js",
  "/shared/dice.js",
  "/shared/fx.js",
  "/shared/game-head.js",
  "/shared/how-to.js",
  "/shared/i18n.js",
  "/shared/names.js",
  "/shared/pass.js",
  "/shared/storage.js",
  "/shared/theme.js",
  "/shared/ui.css",
  "/shared/wake-lock.js",
  "/style.css"
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(VERSION).then((cache) =>
      Promise.all(
        ASSETS.map((url) =>
          cache.add(url).catch(() => {
            /* optional asset */
          }),
        ),
      ),
    ),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  e.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res && res.status === 200 && res.type === "basic") {
            const copy = res.clone();
            caches.open(VERSION).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => {
          if (req.mode === "navigate") return caches.match("/offline.html");
          return new Response("", { status: 504 });
        });
    }),
  );
});

self.addEventListener("message", (e) => {
  if (e.data === "SKIP_WAITING") self.skipWaiting();
});
