#!/usr/bin/env node
// Regenerate /sw.js so that its precache list matches the repo exactly.
// Run: node scripts/build-sw.mjs
//
// Bumps VERSION based on timestamp (monotonic within each deploy).
// The precache list includes shell, icons, and every game's static files.

import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";

const root = fileURLToPath(new URL("..", import.meta.url));
// BASE lets us build the SW for a sub-path deployment (e.g. "/private").
// SW_OUT lets the subpath builder point this at its dist/sw.js.
const BASE = (process.env.BASE || "").replace(/\/$/, "");
const OUT = process.env.SW_OUT || join(root, "sw.js");
const withBase = (p) => (p === "/" ? (BASE || "") + "/" : BASE + p);

const SHELL = [
  "/",
  "/index.html",
  "/offline.html",
  "/style.css",
  "/hub.css",
  "/hub.js",
  "/games.js",
  "/manifest.webmanifest",
].map(withBase);

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith(".")) continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function urlsUnder(subdir, { extensions = null } = {}) {
  const abs = join(root, subdir);
  try {
    return walk(abs)
      .filter((p) => !extensions || extensions.some((e) => p.endsWith(e)))
      .map((p) => "/" + relative(root, p).split(sep).join("/"));
  } catch {
    return [];
  }
}

const sharedFiles = urlsUnder("shared").map(withBase);
const iconFiles = urlsUnder("icons").map(withBase);
const games = readdirSync(join(root, "games")).filter((n) => {
  try { return statSync(join(root, "games", n)).isDirectory(); } catch { return false; }
});
const gameFiles = games.flatMap((slug) => {
  const urls = new Set();
  urls.add(withBase(`/games/${slug}/`));
  for (const f of walk(join(root, "games", slug))) {
    urls.add(withBase("/" + relative(root, f).split(sep).join("/")));
  }
  return [...urls];
});
const rootExtra = ["/og-image.png"].map(withBase);

const assets = [
  ...SHELL,
  ...sharedFiles,
  ...iconFiles,
  ...gameFiles,
  ...rootExtra,
].filter((v, i, a) => a.indexOf(v) === i).sort();

// Build identifier — git short SHA + content hash. Avoids leaking build
// timestamps, while still bumping when files change (so SW cache invalidates
// even on uncommitted edits in dev).
function gitShort() {
  try {
    return execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString().trim();
  } catch {
    return "nogit";
  }
}
function contentHash() {
  const h = createHash("sha256");
  for (const url of assets) {
    h.update(url + "\n");
    const rel = url.replace(/^\//, "").replace(/\/$/, "/index.html");
    try { h.update(readFileSync(join(root, rel))); } catch { /* optional */ }
  }
  return h.digest("hex").slice(0, 8);
}
const VERSION = `dolanan-${gitShort()}-${contentHash()}`;

const sw = `/* Dolanan service worker — cache-first precache of app shell + games.
 * AUTO-GENERATED by scripts/build-sw.mjs. Do not hand-edit the ASSETS list;
 * run \`node scripts/build-sw.mjs\` after adding/renaming files.
 */
const VERSION = ${JSON.stringify(VERSION)};

const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(VERSION).then((cache) =>
      Promise.all(
        ASSETS.map((url) =>
          cache.add(url).catch(() => {
            /* optional asset */
          }),
        ),
      ),
    ),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // EVERYTHING cache-first so HTML and JS/CSS update atomically under the
  // same VERSION cache. Previously HTML was network-first, which produced a
  // window where new HTML (with new data-i18n keys) was paired with old
  // cached JS that hadn't learned those keys yet — users saw raw keys like
  // "hub.about" flash through. By tying HTML to the same cache generation as
  // the JS that consumes it, a deploy only becomes visible AFTER the new SW
  // activates and the auto-update controllerchange handler reloads the page.
  // Network fallback handles first visits (cache empty) and offline.
  const isNavigate = req.mode === "navigate";
  e.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res && res.status === 200 && res.type === "basic") {
            const copy = res.clone();
            caches.open(VERSION).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() =>
          isNavigate
            ? caches.match("/offline.html")
            : new Response("", { status: 504 })
        );
    }),
  );
});

self.addEventListener("message", (e) => {
  if (e.data === "SKIP_WAITING") self.skipWaiting();
});
`;

writeFileSync(OUT, sw);
console.log(`Wrote ${OUT}`);
console.log(`VERSION: ${VERSION}`);
console.log(`Precached ${assets.length} assets`);
