#!/usr/bin/env node
// Regenerate /sw.js so that its precache list matches the repo exactly.
// Run: node scripts/build-sw.mjs
//
// Bumps VERSION based on timestamp (monotonic within each deploy).
// The precache list includes shell, icons, and every game's static files.

import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const OUT = join(root, "sw.js");

const SHELL = [
  "/",
  "/index.html",
  "/offline.html",
  "/style.css",
  "/hub.css",
  "/hub.js",
  "/games.js",
  "/manifest.webmanifest",
];

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith(".")) continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function urlsUnder(subdir, { extensions = null } = {}) {
  const abs = join(root, subdir);
  try {
    return walk(abs)
      .filter((p) => !extensions || extensions.some((e) => p.endsWith(e)))
      .map((p) => "/" + relative(root, p).split(sep).join("/"));
  } catch {
    return [];
  }
}

const sharedFiles = urlsUnder("shared");
const iconFiles = urlsUnder("icons");
const games = readdirSync(join(root, "games")).filter((n) => {
  try { return statSync(join(root, "games", n)).isDirectory(); } catch { return false; }
});
const gameFiles = games.flatMap((slug) => {
  const urls = new Set();
  urls.add(`/games/${slug}/`);
  for (const f of walk(join(root, "games", slug))) {
    urls.add("/" + relative(root, f).split(sep).join("/"));
  }
  return [...urls];
});
const rootExtra = ["/og-image.png"];

const assets = [
  ...SHELL,
  ...sharedFiles,
  ...iconFiles,
  ...gameFiles,
  ...rootExtra,
].filter((v, i, a) => a.indexOf(v) === i).sort();

const VERSION = `dolanan-${new Date().toISOString().slice(0, 19).replace(/[:T-]/g, "")}`;

const sw = `/* Dolanan service worker — cache-first precache of app shell + games.
 * AUTO-GENERATED by scripts/build-sw.mjs. Do not hand-edit the ASSETS list;
 * run \`node scripts/build-sw.mjs\` after adding/renaming files.
 */
const VERSION = ${JSON.stringify(VERSION)};

const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(VERSION).then((cache) =>
      Promise.all(
        ASSETS.map((url) =>
          cache.add(url).catch(() => {
            /* optional asset */
          }),
        ),
      ),
    ),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  e.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res && res.status === 200 && res.type === "basic") {
            const copy = res.clone();
            caches.open(VERSION).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => {
          if (req.mode === "navigate") return caches.match("/offline.html");
          return new Response("", { status: 504 });
        });
    }),
  );
});

self.addEventListener("message", (e) => {
  if (e.data === "SKIP_WAITING") self.skipWaiting();
});
`;

writeFileSync(OUT, sw);
console.log(`Wrote ${OUT}`);
console.log(`VERSION: ${VERSION}`);
console.log(`Precached ${assets.length} assets`);
