// Truth or Dare — offline prompt pool. Keep prompts friendly & safe.

export const PROMPTS = {
  en: {
    truth: [
      "What's a small lie you told this week?",
      "What's your most embarrassing childhood memory?",
      "Name one thing you've been avoiding lately.",
      "What's the silliest thing you've cried about?",
      "Share a habit you wish you could break.",
      "What's the worst advice you've followed?",
      "Who in this room would you trust with a secret?",
      "What's the corniest pick-up line you've used or heard?",
      "Tell us about your worst haircut.",
      "What's your go-to karaoke song?",
      "Who was your first crush and why?",
      "What app do you open first every morning?",
      "What's your weirdest food combination?",
      "What TV show do you secretly love?",
      "What's the last thing you searched online?",
      "What's a skill you wish you had?",
      "Have you ever pretended to know someone?",
      "Tell us a compliment you'll never forget.",
      "Describe your perfect lazy day.",
      "What's a pet peeve most people don't share?",
    ],
    dare: [
      "Text the 5th contact in your phone a random compliment.",
      "Do your best impression of someone in the room.",
      "Sing the chorus of the last song you listened to.",
      "Speak in an accent for the next two turns.",
      "Try to lick your elbow. (Seriously.)",
      "Do 10 jumping jacks while narrating dramatically.",
      "Let the group rename a contact in your phone.",
      "Do a 10-second interpretive dance to an imaginary beat.",
      "Eat something without using your hands.",
      "Call a friend and tell a terrible joke.",
      "Post an emoji-only status for one hour.",
      "Balance a shoe on your head for 30 seconds.",
      "Read your last message aloud in a dramatic voice.",
      "Do a cartwheel — or the safest version you can.",
      "Speak only in questions for one minute.",
      "Let the group pick your next app background.",
      "Mime being a chef for 20 seconds without speaking.",
      "Do a push-up (or a wall push-up) after each word of your name.",
      "Eat a spoonful of whatever's in the fridge.",
      "Recite the alphabet backwards.",
    ],
  },
  id: {
    truth: [
      "Apa kebohongan kecil terakhir yang kamu bilang?",
      "Ceritakan kenangan paling memalukan waktu kecil.",
      "Apa yang sedang kamu hindari akhir-akhir ini?",
      "Hal paling konyol yang pernah bikin kamu nangis?",
      "Kebiasaan apa yang ingin kamu hentikan?",
      "Nasihat terburuk yang pernah kamu turuti?",
      "Siapa di sini yang paling bisa dipercaya rahasianya?",
      "Rayuan paling gombal yang pernah kamu pakai?",
      "Potongan rambut terburuk yang pernah kamu punya?",
      "Lagu andalan kamu di karaoke?",
      "Siapa cinta monyet pertamamu dan kenapa?",
      "Aplikasi apa yang pertama kamu buka tiap pagi?",
      "Kombinasi makanan paling aneh versimu?",
      "Acara TV apa yang diam-diam kamu suka?",
      "Apa pencarian terakhirmu di internet?",
      "Keahlian apa yang ingin kamu miliki?",
      "Pernah pura-pura kenal seseorang?",
      "Pujian yang tak pernah kamu lupa?",
      "Gambarkan hari malas yang sempurna.",
      "Hal kecil yang bikin kamu kesal, tapi orang lain biasa saja?",
    ],
    dare: [
      "Kirim pujian ke kontak ke-5 di HP-mu.",
      "Tirukan gaya bicara seseorang di ruangan ini.",
      "Nyanyikan reff lagu terakhir yang kamu dengar.",
      "Bicara dengan logat tertentu 2 giliran ke depan.",
      "Coba jilat sikumu sendiri. (Serius.)",
      "Lakukan 10 jumping jacks sambil narasi dramatis.",
      "Biarkan grup ganti nama satu kontak di HP-mu.",
      "Tari 10 detik bebas tanpa musik.",
      "Makan sesuatu tanpa pakai tangan.",
      "Telepon teman dan ceritakan lelucon terburukmu.",
      "Pasang status hanya emoji selama 1 jam.",
      "Seimbangkan sepatu di kepala selama 30 detik.",
      "Bacakan pesan terakhirmu dengan suara dramatis.",
      "Lakukan gerakan salto versi paling aman.",
      "Bicara hanya pakai pertanyaan selama 1 menit.",
      "Biarkan grup pilih wallpaper HP barumu.",
      "Peragakan koki sibuk 20 detik tanpa suara.",
      "Lakukan 1 push-up per huruf di namamu.",
      "Makan sesendok apapun yang ada di kulkas.",
      "Bacakan abjad dari belakang.",
    ],
  },
  jw: {
    truth: [
      "Apa gorohan cilik sing kokucapake minggu iki?",
      "Critakna kenangan paling isin wektu cilik.",
      "Apa sing lagi kokhindari akhir-akhir iki?",
      "Bab paling konyol sing tau gawe kok nangis?",
      "Kebiasan apa sing pengin kok lereni?",
      "Pitutur paling ala sing tau kokturuti?",
      "Sapa ing kene sing paling isa dipercaya rahasiane?",
      "Rayuan paling gombal sing tau koknggo utawa krungu?",
      "Potongan rambut paling ala kok piye?",
      "Lagu andhalanmu ing karaoke?",
      "Sapa tresna pisananmu, lan ngopo?",
      "Aplikasi apa sing kokbukak dhisik saben esuk?",
      "Kombinasi panganan paling aneh menurut kok?",
      "Acara TV apa sing meneng-meneng koksenengi?",
      "Pencarian pungkasan kok nang internet apa?",
      "Keahlian apa sing pengin kokduweni?",
      "Tau pura-pura kenal karo wong?",
      "Pujian sing ora nate kok lali?",
      "Gambarna dina kesel sing sempurna.",
      "Bab cilik sing gawe kok nesu, wong liya biasa wae?",
    ],
    dare: [
      "Kirimi pujian menyang kontak nomer 5 HP-mu.",
      "Tirokna gaya wong ing ruangan iki.",
      "Tembangna reff lagu pungkasan sing kokrungu.",
      "Ngomong nganggo logat tertentu 2 giliran.",
      "Cobak dilat sikumu. (Tenanan.)",
      "Lakonana 10 jumping jacks karo narasi dramatis.",
      "Idzinake grup ngganti jeneng kontak ing HP-mu.",
      "Jogedana 10 detik tanpa musik.",
      "Mangana apa wae tanpa nggo tangan.",
      "Telponana kanca lan critakna guyon paling ala.",
      "Gawanana status mung emoji sak jam.",
      "Seimbangna sepatu ing sirah 30 detik.",
      "Wacakna pesen pungkasanmu nganggo swara dramatis.",
      "Lakonana salto versi paling aman.",
      "Ngomong mung nganggo pitakon sak menit.",
      "Idzinake grup milih wallpaper HP-mu.",
      "Peragakna koki sibuk 20 detik tanpa swara.",
      "Lakonana 1 push-up saben aksara jenengmu.",
      "Mangana sesendok apa wae ing kulkas.",
      "Wacakna abjad saka mburi.",
    ],
  },
};
